name       : libart_lgpl
version    : 2.3.21
release    : 2
source     :
    - https://download.gnome.org/sources/libart_lgpl/2.3/libart_lgpl-2.3.21.tar.gz : 2a10b1c884bb37c7bd5c5eba59dbd0d28bf68e64a42d7f2083c836f60f8e98fa
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : Libart is a library for high-performance 2D graphics.
description: |
    Libart is a library for high-performance 2D graphics. Libart supports a very powerful imaging model, basically the same as SVG and the Java 2D API. It includes all PostScript imaging operations, and adds antialiasing and alpha-transparency. Libart is also highly tuned for incremental rendering. It contains data structures and algorithms suited to rapid, precise computation of Region of Interest, as well as a two-phase rendering pipeline optimized for interactive display.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
