name       : libart_lgpl
version    : 2.3.21
release    : 1
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/libart_lgpl/2.3/libart_lgpl-2.3.21.tar.bz2 : fdc11e74c10fc9ffe4188537e2b370c0abacca7d89021d4d303afdf7fd7476fa
license    : LGPL-2.0
summary    : Libart is a library for high-performance 2D graphics.
description: |
    Libart is a library for high-performance 2D graphics. Libart supports a very powerful imaging model, basically the same as SVG and the Java 2D API. It includes all PostScript imaging operations, and adds antialiasing and alpha-transparency. Libart is also highly tuned for incremental rendering. It contains data structures and algorithms suited to rapid, precise computation of Region of Interest, as well as a two-phase rendering pipeline optimized for interactive display.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
